#! /usr/bin/env python
# encoding: utf-8

bld.program(
	packages      = 'gtk+-2.0',
	target        = 'vtime',
	uselib        = 'GTK GLIB',
	source        = ['MainWindow.vala','About.vala', 'TimerModel.vala'],
	vala_defines  = ['DEBUG']
	)

